export enum WorkerMessageEnum {
  UPBIT_SYMBOL_LIST = 'UPBIT_SYMBOL_LIST',
  UPBIT_SYMBOL_TRADE_DATA = 'UPBIT_SYMBOL_TRADE_DATA',
  UPBIT_SYMBOLS_RESTAPI_TRADE_DATA = 'UPBIT_SYMBOLS_RESTAPI_TRADE_DATA',
  BINANCE_SYMBOLS_DATA = 'BINANCE_SYMBOLS_DATA',
}
