name: CI/CD Pipeline hy_toy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: 🧪 CI Test (pull_request)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧹 Run ESLint
        run: npm run lint

      - name: 🧪 Run tests
        run: npm run test

  deploy:
    name: 🚀 Deploy to GitHub Pages (main push)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🛠 Build project
        run: npm run build

      - name: 👤 Configure Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: 🚀 Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
